version: '3'
services:

  carsindfw_app:
    container_name: carsindfw-app
    build: ./backend
    #    restart: always
    volumes:
      - ./backend/src:/var/www
#    environment:
#      - "XDEBUG_CONFIG=remote_host=localhost remote_port=9000 remote_enable=1 remote_autostart = 1"
#      - "PHP_IDE_CONFIG=serverName=xdebug-docker"

  carsindfw_nginx:
    container_name: carsindfw-nginx
    build: ./nginx
    #    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./backend/src:/var/www
    depends_on:
      - carsindfw_app