version: '3'
services:

  carsindfw_app:
    container_name: carsindfw-app
    build: ./backend
    #    restart: always
    volumes:
      - ./backend/src:/var/www
#    environment:
#      - "XDEBUG_CONFIG=client_host=localhost client_port=9003 mode=debug start_with_request=1 idekey=PHPSTORM discover_client_host=on"
#      - "XDEBUG_MODE=debug"
#      - "PHP_IDE_CONFIG=serverName=xdebug-docker"

  carsindfw_nginx:
    container_name: carsindfw-nginx
    build: ./nginx
    #    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./backend/src:/var/www
    depends_on:
      - carsindfw_app